on: [push]
jobs:
  build:
    name: build-${{matrix.target}}
    runs-on: docker
    strategy:
      matrix:
        target: ["linux", "windows", "macos"]
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
        with:
          github-server-url: https://forge.wolo.dev
      - name: Build
        id: build
        uses: https://github.com/mlm-games/godot-build-action@v1.3.1
        with:
          EXPORT_PRESET_NAME: ${{matrix.target}}
      - name: Push artifacts
        uses: https://data.forgejo.org/actions/upload-artifact@v4
        with:
          name: "lt-${{matrix.target}}"
          path: ${{ steps.build.outputs.build }}
          compression-level: 9
      - name: Upload to itchio auto-builds
        uses: https://github.com/KikimoraGames/itch-publish@v0.0.3
        with:
          butlerApiKey: ${{secrets.BUTLER_API_KEY}}
          gameData: ${{ steps.build.outputs.build }}
          itchUsername: hwcgames
          itchGameId: hwcrpg
          buildChannel: auto-${{ matrix.target }}
          buildNumber: ${{ needs.version.outputs.version_hash }}
